name: Deploy to Fly.io

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Fly CLI
      run: flyctl auth login --email ${{ secrets.FLY_EMAIL }} --password ${{ secrets.FLY_PASSWORD }}
      uses: superfly/flyctl-actions/setup-flyctl@master
      with:
        token: ${{ secrets.FLY_API_TOKEN }}

    - name: Deploy to Fly.io
      run: flyctl deploy
